// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC7R8DIHiST_-_NSh1jN-XJsNXNN_BVOQ',
    appId: '1:691230535529:web:4840abd2daaba45aea17f8',
    messagingSenderId: '691230535529',
    projectId: 'tugasmandiri-3788a',
    authDomain: 'tugasmandiri-3788a.firebaseapp.com',
    storageBucket: 'tugasmandiri-3788a.firebasestorage.app',
    measurementId: 'G-EDB3Y8ZGRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR_Bs7cvLnQJyczoQX_29KmHA1pwR3rZY',
    appId: '1:691230535529:android:dc3f60ed1f656bbdea17f8',
    messagingSenderId: '691230535529',
    projectId: 'tugasmandiri-3788a',
    storageBucket: 'tugasmandiri-3788a.firebasestorage.app',
  );
}
